---
apiVersion: v2
description: RomM (Rom Manager) is a web based retro roms manager integrated with IGDB.
name: romm
type: application
home: https://zurdi15.github.io/romm/
icon: https://raw.githubusercontent.com/CrystalNET-org/helm-romm/main/chart/icon.png
version: 0.3.2
# renovate: image=zurdi15/romm
appVersion: "2.3.1"
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: psych0d0g
    email: h@xx0r.eu
sources:
  - https://github.com/zurdi15/romm
  - https://github.com/CrystalNET-org/helm-romm
dependencies:
  - name: redis
    version: ~18.7.0
    repository: https://charts.bitnami.com/bitnami
    alias: redis
    condition: redis.enabled
  - name: mariadb
    version: ~20.4.0
    repository: https://charts.bitnami.com/bitnami
    alias: mariadb
    condition: mariadb.enabled
