apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "romm.fullname" . }}
  labels:
    {{- include "romm.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "romm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "romm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          {{- if and (.Values.redis.enabled) (.Values.romm.config.auth.enabled) -}}
          - name: ROMM_AUTH_ENABLED
            value: "true"
          {{- if .Values.romm.config.auth.existing_secret -}}
          - name: ROMM_AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: romm-credentials
                key: romm-user
          - name: ROMM_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: romm-credentials
                key: romm-pass
          {{- else -}}
          - name: ROMM_AUTH_USERNAME
            value: {{ .Values.romm.config.auth.username }}
          - name: ROMM_AUTH_PASSWORD
            value: {{ .Values.romm.config.auth.password }}
          {{- end -}}
          - name: ROMM_AUTH_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: romm-shared-secret
                key: auth-secret
          {{- end }}
          {{- /*
          # Database configuration
          */}}
          {{- if .Values.mariadb.enabled }}
          - name: ROMM_DB_DRIVER
            value: "mariadb"
          - name: DB_HOST
            value: {{ printf "%s-mariadb" .Release.Name | quote }}
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: {{ .Values.mariadb.auth.username | quote }}
          - name: DB_NAME
            value: {{ .Values.mariadb.auth.database | quote }}
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-mariadb" .Release.Name | quote }}
                key: mariadb-password
          {{- else if contains "mariadb" .Values.romm.config.database.type }}
          - name: ROMM_DB_DRIVER
            value: "mariadb"
          - name: DB_HOST
            value: {{ .Values.romm.config.database.mariadb.host | quote }}
          - name: DB_PORT
            value: {{ .Values.romm.config.database.mariadb.port | quote }}
          - name: DB_USER
            value: {{ .Values.romm.config.database.mariadb.user | quote }}
          - name: DB_NAME
            value: {{ .Values.romm.config.database.mariadb.schema | quote }}
          - name: DB_PASSWD
            value: {{ .Values.romm.config.database.mariadb.pass | quote }}
          {{- else }}
          - name: ROMM_DB_DRIVER
            value: "sqlite"
          {{- end }}
          {{- /*
          # END Database configuration
          */}}
          {{- /*
          # Redis enabling if desired
          */}}
          {{- if .Values.redis.enabled }}
          - name: ENABLE_EXPERIMENTAL_REDIS
            value: "true"
          - name: REDIS_HOST
            value: {{ printf "%s-redis-headless" .Release.Name | quote }}
          - name: REDIS_PORT
            value: {{ .Values.redis.redisPort | quote }}
          {{- if .Values.redis.auth.enabled }}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: romm-redis
                key: redis-password
          {{- end }}
          {{- end }}
          {{- /*
          # END Redis enabling if desired
          */}}
          - name: ENABLE_RESCAN_ON_FILESYSTEM_CHANGE
            value: {{ .Values.romm.config.filesystem_watcher.enabled | default true | quote }}
          - name: RESCAN_ON_FILESYSTEM_CHANGE_DELAY
            value: {{ .Values.romm.config.filesystem_watcher.scan_delay | default 5 | quote }}
          - name: ENABLE_SCHEDULED_RESCAN
            value: {{ .Values.romm.config.scheduled_tasks.filesystem_scan.enabled | default true | quote }}
          - name: SCHEDULED_RESCAN_CRON
            value: {{ .Values.romm.config.scheduled_tasks.filesystem_scan.cron | quote }}
          - name: ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB
            value: {{ .Values.romm.config.scheduled_tasks.switch_titledb_update.enabled | default true | quote }}
          - name: SCHEDULED_UPDATE_SWITCH_TITLEDB_CRON
            value: {{ .Values.romm.config.scheduled_tasks.switch_titledb_update.cron | quote }}
          - name: ENABLE_SCHEDULED_UPDATE_MAME_XML
            value: {{ .Values.romm.config.scheduled_tasks.mame_xml_update.enabled | default true | quote }}
          - name: SCHEDULED_UPDATE_MAME_XML_CRON
            value: {{ .Values.romm.config.scheduled_tasks.mame_xml_update.cron | quote }}
          {{- if .Values.romm.config.igdb_api.existing_secret }}
          - name: IGDB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: romm-credentials
                key: igdb-client-id
          - name: IGDB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: romm-credentials
                key: igdb-client-secret
          {{- else }}
          - name: IGDB_CLIENT_ID
            value: {{ .Values.romm.config.igdb_api.client_id | quote }}
          - name: IGDB_CLIENT_SECRET
            value: {{ .Values.romm.config.igdb_api.client_secret | quote }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: resources
              mountPath: /romm/resources
            - name: logs
              mountPath: /romm/logs
            - name: database
              mountPath: /romm/database
            - name: library
              mountPath: /romm/library
            - name: temp
              mountPath: /tmp/
            - name: romm-config
              mountPath: /romm/config.yml
              subPath: config.yml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: romm-config
          configMap:
            name: {{ include "romm.fullname" . }}-config
            items:
            - key: config.yml
              path: config.yml
        - name: resources
          {{- if .Values.persistence.resources.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "romm.fullname" . }}-resources
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: logs
          {{- if .Values.persistence.logs.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "romm.fullname" . }}-logs
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: database
          {{- if .Values.persistence.database.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "romm.fullname" . }}-database
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: library
          {{- if .Values.mediaVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "romm.fullname" $ }}-mediavol-{{ .Values.mediaVolume.name }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: temp
          emptyDir: { }